[package]
name = "graviola"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1"
getrandom = "0.2"

[dev-dependencies]
hex = { version = "0.4", features = ["serde"] }
proptest = "1.5.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
